import type { Metadata } from "next";
<<<<<<< HEAD
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar"; // Import the new client navbar
import { directus } from "@/lib/directus";
import { readSingleton } from "@directus/sdk";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Infysmart | Enterprise Security & Automation",
  description: "An unit of Infygru Private Limited",
};

export default async function RootLayout({
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
>>>>>>> 77bd4f21ae6f899b48680ec69e65e85793de4e8e
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
<<<<<<< HEAD
  // Fetch settings once on the server side
  const settings = await directus.request(readSingleton('global_settings'));

  return (
    <html lang="en" className="scroll-smooth">
      <body className={inter.className}>
        {/* Pass settings as props to the Client Component Navbar */}
        <Navbar settings={settings} />
        {children}
        {/* Add Footer here later */}
      </body>
    </html>
  );
}
=======
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
>>>>>>> 77bd4f21ae6f899b48680ec69e65e85793de4e8e
