
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy | Infysmart Solutions",
  description: "Privacy Policy outlining how Infysmart Solutions collects, uses, and protects your data.",
  alternates: { canonical: 'https://infysmart.com/privacy' },
  robots: { index: false, follow: false }
};

export default function PrivacyPage() {
  return (
    <div className="bg-white min-h-screen py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-3xl font-extrabold text-gray-900 sm:text-4xl mb-8">
          Privacy Policy
        </h1>
        <div className="prose prose-blue max-w-none text-gray-500">
          <p className="mb-4">Last Updated: {new Date().toLocaleDateString()}</p>

          <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">1. Information We Collect</h2>
          <p className="mb-4">
            We collect information you provide directly to us, such as when you create an account, subscribe to our newsletter, request customer support, or otherwise communicate with us. The types of information we may collect include your name, email address, postal address, phone number, and any other information you choose to provide.
          </p>

          <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">2. How We Use Your Information</h2>
          <p className="mb-4">
            We use the information we collect to provide, maintain, and improve our services, including to:
          </p>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li>Process transactions and send related information</li>
            <li>Send you technical notices, updates, security alerts, and support and administrative messages</li>
            <li>Respond to your comments, questions, and requests</li>
            <li>Communicate with you about products, services, offers, and events</li>
          </ul>

          <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">3. Log Data</h2>
          <p className="mb-4">
            We want to inform you that whenever you visit our Service, we collect information that your browser sends to us that is called Log Data. This Log Data may include information such as your computer’s Internet Protocol (“IP”) address, browser version, pages of our Service that you visit, the time and date of your visit, the time spent on those pages, and other statistics.
          </p>

          <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">4. Cookies</h2>
          <p className="mb-4">
            Our website uses &quot;cookies&quot; to collect information and to improve our Service. You have the option to either accept or refuse these cookies, and know when a cookie is being sent to your computer. If you choose to refuse our cookies, you may not be able to use some portions of our Service.
          </p>

          <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">5. Security</h2>
          <p className="mb-4">
            We value your trust in providing us your Personal Information, thus we are striving to use commercially acceptable means of protecting it. But remember that no method of transmission over the internet, or method of electronic storage is 100% secure and reliable, and we cannot guarantee its absolute security.
          </p>

          <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">6. Data Pertaining to Security Installations</h2>
          <p className="mb-4">
            Given the nature of our business (CCTV, Biometrics, and Access Control), InfySmart Solutions explicitly states that we do <strong>not</strong> have remote access to, nor do we store, the video footage, biometric templates, or access logs generated by the systems installed at client premises, unless explicitly contracted to provide remote monitoring or cloud backup services.
          </p>
          <p className="mb-4">
            All data generated by physical security systems remains the sole property and responsibility of the client. During Annual Maintenance Contract (AMC) visits, our technicians may view live feeds or access logs purely for diagnostic and troubleshooting purposes. No data is copied, transmitted, or backed up to InfySmart servers without written authorization from the client&apos;s authorized representative.
          </p>

          <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">7. Third-Party Services</h2>
          <p className="mb-4">
            We may employ third-party companies and individuals due to the following reasons:
            <ul className="list-disc pl-6 mt-2 mb-4 space-y-2">
              <li>To facilitate our Service (e.g., cloud hosting providers, payment gateways);</li>
              <li>To provide the Service on our behalf (e.g., third-party logistics for material delivery);</li>
              <li>To perform Service-related services (e.g., specialized sub-contractors for heavy civil work); or</li>
              <li>To assist us in analyzing how our Service is used.</li>
            </ul>
            We want to inform our Service users that these third parties have access to your Personal Information only to perform the tasks assigned to them on our behalf. However, they are obligated not to disclose or use the information for any other purpose.
          </p>

          <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">8. Children&apos;s Privacy</h2>
          <p className="mb-4">
            Our Services do not address anyone under the age of 13. We do not knowingly collect personally identifiable information from children under 13. In the case we discover that a child under 13 has provided us with personal information, we immediately delete this from our servers. If you are a parent or guardian and you are aware that your child has provided us with personal information, please contact us so that we will be able to do necessary actions.
          </p>

          <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4">9. Changes to This Privacy Policy</h2>
          <p className="mb-4">
            We may update our Privacy Policy from time to time. Thus, we advise you to review this page periodically for any changes. We will notify you of any changes by posting the new Privacy Policy on this page. These changes are effective immediately, after they are posted on this page.
          </p>

          <h2 className="text-2xl font-bold text-gray-800 mt-12 mb-6 border-b pb-2">Frequently Asked Questions regarding Privacy</h2>

          <div className="space-y-6">
            <div className="bg-gray-50 p-6 rounded-lg border border-gray-100">
              <h4 className="font-bold text-gray-900 mb-2">Can InfySmart view my home CCTV footage remotely?</h4>
              <p className="text-sm">
                No. When we configure your Video Door Phone or CCTV for mobile viewing, the system uses P2P (Peer-to-Peer) encryption algorithms provided by the manufacturer (e.g., Hikvision, Dahua). The video stream travels directly from your DVR/NVR to your registered smartphone account. InfySmart does not possess the administrative passwords or decryption keys required to view your live or recorded footage remotely.
              </p>
            </div>

            <div className="bg-gray-50 p-6 rounded-lg border border-gray-100">
              <h4 className="font-bold text-gray-900 mb-2">What happens to our biometric data if we discontinue your AMC?</h4>
              <p className="text-sm">
                As the biometric templates (fingerprint/face data) are stored locally on the hardware devices installed at your premises (or on your own internal servers if using an on-premise HRMS), the data remains entirely in your control. InfySmart does not retain any copies of employee biometric data. Upon terminating our AMC, your HR or IT department simply continues managing the devices as usual without any data loss.
              </p>
            </div>

            <div className="bg-gray-50 p-6 rounded-lg border border-gray-100">
              <h4 className="font-bold text-gray-900 mb-2">How do you handle data collected during site surveys?</h4>
              <p className="text-sm">
                During initial site surveys, our engineers may take photographs of building layouts, electrical panels, and entry points to design an accurate Technical Architecture Document (TAD). These images are strictly confidential, stored on encrypted enterprise drives, and are used solely for the purpose of formulating the project quote and execution plan. We do not use client site blueprints or security maps for marketing purposes without explicit consent.
              </p>
            </div>
          </div>

          <h2 className="text-2xl font-bold text-gray-800 mt-12 mb-4">Contact Us</h2>
          <p className="mb-4">
            If you have any questions or suggestions about our Privacy Policy, do not hesitate to contact our Data Protection Officer at <strong>privacy@infysmart.com</strong>.
          </p>
        </div>
      </div>
    </div>
  );
}